version: '3'
services:
  api:
    image: node:8.15.0
    volumes:
      - ./backend:/backend
    ports:
      - 3000:3000
    command: >
      bash -c "cd backend/ && npm i -g yarn
      && yarn && yarn build && yarn start"